import type { StationSeed } from '../types'

/**
 * Approximate coordinates as written by hand. GloFAS returns the largest river
 * within a ~5 km cell, so these are refined by `npm run validate:stations`;
 * the app reads the validated result through `stations.ts`.
 */
export const STATION_SEEDS: readonly StationSeed[] = [
  {
    id: 'dnipro-kyiv',
    river: 'Дніпро',
    place: 'Київ',
    basin: 'dnipro',
    focus: true,
    lat: 50.45,
    lon: 30.57,
    expectedMeanRange: [1000, 1500],
  },
  {
    id: 'desna-chernihiv',
    river: 'Десна',
    place: 'Чернігів',
    basin: 'dnipro',
    focus: true,
    lat: 51.47,
    lon: 31.31,
    expectedMeanRange: [250, 400],
  },
  {
    id: 'desna-novhorod-siverskyi',
    river: 'Десна',
    place: 'Новгород-Сіверський',
    basin: 'dnipro',
    focus: true,
    lat: 52.0,
    lon: 33.27,
    expectedMeanRange: [150, 300],
  },
  {
    id: 'prypiat-chornobyl',
    river: 'Прип’ять',
    place: 'Чорнобиль',
    basin: 'dnipro',
    focus: true,
    lat: 51.28,
    lon: 30.23,
    expectedMeanRange: [350, 500],
  },
  {
    id: 'dnister-zalishchyky',
    river: 'Дністер',
    place: 'Заліщики',
    basin: 'dnister',
    focus: false,
    lat: 48.64,
    lon: 25.73,
    expectedMeanRange: [150, 300],
  },
  {
    id: 'prut-chernivtsi',
    river: 'Прут',
    place: 'Чернівці',
    basin: 'danube',
    focus: false,
    lat: 48.31,
    lon: 25.93,
    expectedMeanRange: [50, 100],
  },
  {
    id: 'tysa-vylok',
    river: 'Тиса',
    place: 'Вилок',
    basin: 'danube',
    focus: false,
    lat: 48.1,
    lon: 22.83,
    expectedMeanRange: [150, 250],
  },
  {
    id: 'danube-izmail',
    river: 'Дунай',
    place: 'Ізмаїл',
    basin: 'danube',
    focus: false,
    lat: 45.34,
    lon: 28.84,
    expectedMeanRange: [5000, 7000],
  },
  {
    id: 'pivdennyi-buh-pervomaisk',
    river: 'Південний Буг',
    place: 'Первомайськ',
    basin: 'pivdennyi-buh',
    focus: false,
    lat: 48.04,
    lon: 30.85,
    expectedMeanRange: [50, 120],
  },
  {
    id: 'siverskyi-donets-izium',
    river: 'Сіверський Донець',
    place: 'Ізюм',
    basin: 'don',
    focus: false,
    lat: 49.21,
    lon: 37.26,
    expectedMeanRange: [30, 80],
  },
]
